theme: jekyll-theme-cayman

title: Need to fill m prâ—”ject râ—•les involving x â˜ï¸providers with nâ‰ m data nerdsğŸ¤“...

description: ...working from y locations in z timeğŸ•—ğŸ•‘zones? ğŸ˜µâ€ğŸ’«
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com 