theme: jekyll-theme-cayman

title: Hands-on remote data science handovers

description:  that consistently boost intellectual capital for everyone involved
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com