theme: jekyll-theme-cayman

title: We unite sync and async data science
description: "Imagine a distributed team of data nerds pulling off a complex project, and nobody ever says stuff like: <em>But it worked on my machineğŸ¤·&hellip;</em>  That becomes easy with Flexpair: When handing over a task, you talk them through it on an interactive cloud desktop that has been replicated automatically, including your custom dependencies&mdash;in any cloud. And before merging the new feature, you test it there on real data and visualize results togetherğŸ¤."
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com