theme: jekyll-theme-cayman

title: Hands-on remote handovers for data nerds

description: that consistently boost intellectual capital for everyone involved&mdash;across any but personal or planetary boundaries
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com