theme: jekyll-theme-cayman

title: Don't despair! Flexpair ğŸ¤—

description: Demonstrate, collaborate, delegate, meditate, repeatâ™»ï¸
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com