theme: jekyll-theme-cayman

title: We integrate sync and async data science
description: 'Never want to hear again "&hellip;but it worked on my computer and all tests were greenğŸ¥º"? Then you need Flexpair for your team. Interactively review merge requests together on a sharedğŸ¤ cloud desktop. Feel like being in one room, even when working on opposite sides of the globeğŸŒ. And the best: It can be freshly recreated at the push of a button with all dependencies installed and test data prepared for you&mdash;independent of the cloud provider(s) you useâœ…'
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com