theme: jekyll-theme-cayman

title: We integrate sync and async data science
description: 'Are you tired of hearing stuff like "&hellip;but it worked on my computer and all tests were greenğŸ¥º" ever again? Then you need Flexpair for your team. Enjoy the ability to review merge requests togetherğŸ¤ on an interactive cloud desktop. Feel like being in one room, even when working on opposite sides of the globe. And the best: It can be freshly replicated at the push of a buttonğŸ–– with all dependencies installed and test data prepared for you&mdash;on any cloud.'
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com