theme: jekyll-theme-cayman

title: Don't despair &ndash; FlexpairğŸ¤—

description: Demonstrate your ğŸ’¡, collaborate, delegate, meditate, repeat.
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com