theme: jekyll-theme-cayman

title: Need to fill m prâ—”ject râ—•les involving x â˜ï¸providers with nâ‰ m data nerdsğŸ¤“...

description: who work from y locations in z time zones? ğŸ˜µâ€ğŸ’«
github:
  repository_url: https://github.com/jafudi/pairpac

demo:
  demo_url: http://demo.flexpair.com 